version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trek
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: