version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trek
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn trekapi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=trekapi.settings
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./trekapi/media:/usr/share/nginx/html/media  # Mount the media folder into Nginx container
      - ./nginx.conf:/etc/nginx/nginx.conf    # Custom Nginx configuration file
    ports:
      - "80:80"   # Expose HTTP port for Nginx
    depends_on:
      - web

volumes:
  pgdata: